import 'dart:math';

class Product {
  final String name;
  final String imagePath;
  final double currentPrice;
  final double? oldPrice;
  final int? discountPercent;
  final String category;
  final int id;
  bool favorite;
  final List<String> option;
  final int rate;

  Product({
    required this.name,
    required this.imagePath,
    required this.currentPrice,
    this.oldPrice,
    this.discountPercent,
    required this.category,
    required this.id,
    this.favorite = false,
    required this.option,
    required this.rate,
  });
}

final List<Product> _productList = [
  // Watches
  Product(
    name: 'Apple Watch Series 11',
    imagePath: 'assets/products/watches/apple-watch11.png',
    currentPrice: 509.90,
    category: 'watch',
    id: 1,
    option: ['M1', 'M2', 'M3', 'M4'],
    rate: 5,
  ),
  Product(
    name: 'Samsung Galaxy Watch Ultra',
    imagePath: 'assets/products/watches/galaxy-watch-ultra.png',
    currentPrice: 599.99,
    category: 'watch',
    id: 2,
    option: ['U1', 'U2', 'U3', 'U4'],
    rate: 5,
  ),
  Product(
    name: 'Apple Watch SE Gen 2',
    imagePath: 'assets/products/watches/apple-watch-se.png',
    currentPrice: 200.99,
    category: 'watch',
    id: 3,
    option: ['S1', 'S2', 'S3'],
    rate: 4,
  ),
  Product(
    name: 'Samsung Galaxy Watch 7',
    imagePath: 'assets/products/watches/galaxy-watch7.png',
    currentPrice: 200.99,
    category: 'watch',
    id: 4,
    option: ['G1', 'G2', 'G3', 'G4', 'G5'],
    rate: 5,
  ),
  Product(
    name: 'Google Pixel Watch 3',
    imagePath: 'assets/products/watches/pixel-watch.png',
    currentPrice: 319.90,
    category: 'watch',
    id: 5,
    option: ['P1', 'P2', 'P3'],
    rate: 4,
  ),
  Product(
    name: 'Huawei Watch GT 4',
    imagePath: 'assets/products/watches/huawei-watch.png',
    currentPrice: 249.90,
    category: 'watch',
    id: 6,
    option: ['H1', 'H2', 'H3', 'H4'],
    rate: 4,
  ),

  // T-Shirts
  Product(
    name: 'Classic Brown Cotton Tee',
    imagePath: 'assets/products/tshirts/t-shirt1.png',
    currentPrice: 14.99,
    oldPrice: 29.90,
    discountPercent: 50,
    category: 'tshirt',
    id: 7,
    option: ['48', '50', '52', '54', '56', '58'],
    rate: 5,
  ),
  Product(
    name: 'Essential Black T-Shirt',
    imagePath: 'assets/products/tshirts/t-shirt2.png',
    currentPrice: 14.99,
    oldPrice: 29.90,
    discountPercent: 50,
    category: 'tshirt',
    id: 8,
    option: ['36', '38', '40', '42', '44', '46', '48'],
    rate: 5,
  ),
  Product(
    name: 'Heather Grey Crew Neck',
    imagePath: 'assets/products/tshirts/t-shirt3.png',
    currentPrice: 14.99,
    oldPrice: 29.90,
    discountPercent: 50,
    category: 'tshirt',
    id: 9,
    option: ['38', '40', '42'],
    rate: 4,
  ),
  Product(
    name: 'Navy Blue Premium Tee',
    imagePath: 'assets/products/tshirts/t-shirt4.png',
    currentPrice: 19.99,
    category: 'tshirt',
    id: 10,
    option: ['36', '38', '40', '42', '44', '46'],
    rate: 5,
  ),
  Product(
    name: 'Soft Pink Casual Shirt',
    imagePath: 'assets/products/tshirts/t-shirt5.png',
    currentPrice: 14.99,
    oldPrice: 39.90,
    discountPercent: 50,
    category: 'tshirt',
    id: 11,
    option: ['34', '36', '38'],
    rate: 3,
  ),
  Product(
    name: 'Forest Green V-Neck',
    imagePath: 'assets/products/tshirts/t-shirt6.png',
    currentPrice: 19.99,
    category: 'tshirt',
    id: 12,
    option: ['38', '40', '42', '44', '46'],
    rate: 4,
  ),

  // Bags
  Product(
    name: 'Classic Leather Tote Bag',
    imagePath: 'assets/products/bags/bag1.png',
    currentPrice: 19.99,
    oldPrice: 40.90,
    discountPercent: 50,
    category: 'bag',
    id: 13,
    option: ['Classic Black', 'Chestnut Brown', 'Desert Sand'],
    rate: 5,
  ),
  Product(
    name: 'Vintage Messenger Bag',
    imagePath: 'assets/products/bags/bag2.png',
    currentPrice: 19.99,
    oldPrice: 40.90,
    discountPercent: 50,
    category: 'bag',
    id: 14,
    option: ['Vintage Brown', 'Coal Grey', 'Midnight Navy', 'Forest Green'],
    rate: 5,
  ),
  Product(
    name: 'Modern Crossbody Purse',
    imagePath: 'assets/products/bags/bag3.png',
    currentPrice: 19.99,
    oldPrice: 40.90,
    discountPercent: 50,
    category: 'bag',
    id: 15,
    option: ['Slate', 'Mahogany', 'Pearl', 'Amber Rose', 'Lapis'],
    rate: 5,
  ),
  Product(
    name: 'Luxury Designer Handbag',
    imagePath: 'assets/products/bags/bag4.png',
    currentPrice: 19.99,
    oldPrice: 40.90,
    discountPercent: 50,
    category: 'bag',
    id: 16,
    option: ['Monogram Edition', 'Ivory Luxe', 'Obsidian', 'Rose Gold', 'Sable'],
    rate: 4,
  ),
  Product(
    name: 'Travel Backpack Pro',
    imagePath: 'assets/products/bags/bag5.png',
    currentPrice: 19.99,
    oldPrice: 40.90,
    discountPercent: 50,
    category: 'bag',
    id: 17,
    option: ['Explorer Grey', 'Ocean Blue', 'Midnight Black', 'Canyon', 'Sierra'],
    rate: 5,
  ),
  Product(
    name: 'Business Briefcase Elite',
    imagePath: 'assets/products/bags/bag6.png',
    currentPrice: 19.99,
    oldPrice: 40.90,
    discountPercent: 50,
    category: 'bag',
    id: 18,
    option: ['Executive Black', 'Carbon Grey', 'Espresso Brown'],
    rate: 5,
  ),
  Product(
    name: 'Urban Combat Boots',
    imagePath: 'assets/products/boots/boots1.png',
    currentPrice: 89.99,
    oldPrice: 149.90,
    discountPercent: 40,
    category: 'boot',
    id: 19,
    option: ['40', '41', '42', '43', '44', '45'],
    rate: 5,
  ),
  Product(
    name: 'Chelsea Leather Boots',
    imagePath: 'assets/products/boots/boots2.png',
    currentPrice: 129.99,
    category: 'boot',
    id: 20,
    option: ['38', '39', '40', '41', '42', '43'],
    rate: 4,
  ),
  Product(
    name: 'Hiking Trail Boots Pro',
    imagePath: 'assets/products/boots/boots3.png',
    currentPrice: 159.99,
    oldPrice: 219.90,
    discountPercent: 27,
    category: 'boot',
    id: 21,
    option: ['39', '40', '41', '42', '43', '44', '45'],
    rate: 5,
  ),
  Product(
    name: 'Classic Ankle Boots',
    imagePath: 'assets/products/boots/boots4.png',
    currentPrice: 74.99,
    oldPrice: 99.90,
    discountPercent: 25,
    category: 'boot',
    id: 22,
    option: ['36', '37', '38'],
    rate: 3,
  ),
  Product(
    name: 'Winter Snow Boots',
    imagePath: 'assets/products/boots/boots5.png',
    currentPrice: 119.99,
    oldPrice: 199.90,
    discountPercent: 40,
    category: 'boot',
    id: 23,
    option: ['40', '41', '42', '43', '44', '45', '46'],
    rate: 5,
  ),
  Product(
    name: 'Designer Suede Boots',
    imagePath: 'assets/products/boots/boots6.png',
    currentPrice: 189.99,
    category: 'boot',
    id: 24,
    option: ['39', '40', '41', '42', '43', '44'],
    rate: 3,
  ),
];

List<Product> get allProducts => List.from(_productList)..shuffle(Random());
